### ISSUE TITLE
New Method Invocation Type

### ISSUE THREAD

**Issue by AndyWu2015** [gamerson/blade.tools#106]
Hi guys ,  I find there may be some new method invocation types such as :
Indexer.addRelatedEntryFields(new Document(), new Object());
and
Indexer.addRelatedEntryFields(Util.getDoc() , Util.getObj());
and so on, should we consider these cases ?

**Comment by gamerson** [comment]
So "Indexer" is an interface, so I'm not sure how those would be invoked in your example.  Do you have an example in existing 6.2 codebase that you have found?

**Comment by AndyWu2015** [comment]
No , I just assume that case.

**Comment by gamerson** [comment]
Actually methods can't be invoiked directly from the interface class like a static method, so we don't need this type of check.

We just need to find objects of type "Indexer" and look for method invocations.

**Comment by AndyWu2015** [comment]
Sorry, it doesn't about interface , it is just about the ways args passed:
Actually:
Document doc = new Document();
DLIndexer.addRelatedEntryFields(doc);
This is general call —— init a variable first and pass it to method;
But there may be others ways such as:
DLIndexer.addRelatedEntryFields(new Document());
or 
DLIndexer.addRelatedEntryFields(DocUtil.getDoc());
Shoule we consider such kind of args ?
In AST, "new Document()" type is "ClassInstanceCreation" and DocUtil.getDoc() is "MethodInvocation"

**Comment by gamerson** [comment]
But "DLIndexer" is an interface and you can't invoke static methods on it.  You must use an instance of DLIndexer or use DLIndexerUtil? right?

**Comment by AndyWu2015** [comment]
Yeah , sorry again , I just use DLIndexer as an example , we can replace DLIndexer with ServiceContext and so on , I just aim at the args type , It really doesn't matter what the method name is or comes from . I mean if we want to check out different args types we have to  improve our JavaFileChecker.findMethodInvocations method .

**Comment by AndyWu2015** [comment]
fixed
