### ISSUE TITLE
Removed permissionClassName, permissionClassPK, and permissionOwner Parameters from MBMessage API

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#11]
Date:2015-May-27
https://issues.liferay.com/browse/LPS-55877
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#removed-permissionclassname-permissionclasspk-and-permissionowner-parameters-from-mbmessage-api

**Comment by jtydhr88** [comment]
Didn't fix the tag issue yet
