### ISSUE TITLE
Changed Java Package Names for Portlets Extracted as Modules

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#130]
Date: 2015-Jun-29
https://issues.liferay.com/browse/LPS-56383
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#changed-java-package-names-for-portlets-extracted-as-modules

type:java,jsp,properties

**Comment by gamerson** [comment]
Lovett,  We need to include the type here "java,jsp,properties" etc.

On Tue, Jul 14, 2015 at 11:40 AM, Lovett Li <notifications@github.com>
wrote:

> Date: 2015-Jun-29
> https://issues.liferay.com/browse/LPS-56383
>
> https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#changed-java-package-names-for-portlets-extracted-as-modules
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/blade.tools/issues/130>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by lovettli** [comment]
Hey Greg, 
The issue lists many changed java package names .so do our test file need to contain all of the package name or just one?

**Comment by gamerson** [comment]
It needs to contain all of the ones that did change, yes.  Do you have the
entire list?

On Wed, Jul 22, 2015 at 4:00 AM, Lovett Li <notifications@github.com> wrote:

> Hey Greg,
> The issue lists many changed java package names .so do our test file need
> to contain all of the package name or just one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/blade.tools/issues/130#issuecomment-123628899>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by lovettli** [comment]
Yes,i have.i mean our one test file is able to contain many package name code just like 

” package   com.liferay.portlet.bookmarks 
 package   com.liferay.portlet.dynamicdatalists
package    com.liferay.portlet.journal 
package    com.liferay.portlet.polls 
package    com.liferay.portlet.wiki “

is it right?

**Comment by gamerson** [comment]
Yes.

On Wed, Jul 22, 2015 at 9:39 AM, Lovett Li <notifications@github.com> wrote:

> Yes,i have.i mean our one test file is able to contain many package name
> code just like
>
> ” package com.liferay.portlet.bookmarks
> package com.liferay.portlet.dynamicdatalists
> package com.liferay.portlet.journal
> package com.liferay.portlet.polls
> package com.liferay.portlet.wiki “
>
> is it right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/blade.tools/issues/130#issuecomment-123744760>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by lovettli** [comment]
Hey Greg,
The ASTVisitor can visite PackageDeclaration just one. so if we put all of the package code into one test file. The ASTVisitor just is able to visite  the last one. For example , this is our test file
” package com.liferay.portlet.bookmarks
package com.liferay.portlet.dynamicdatalists
package com.liferay.portlet.journal
package com.liferay.portlet.polls
package com.liferay.portlet.wiki “

We want to test all possible case, but PackageDeclaration just is "com.liferay.portlet.wiki" all the time.so if we want test all case. My idea is put each of package name code into different file and put all the file into a folder.
we can change the test path to a directory.
what do you think? thanks.

**Comment by gamerson** [comment]
So the visitor can only check for one package, but our Migrator component
can search for multiple packages.

@Override
protected List<SearchResult> searchJavaFile(File file, JavaFileChecker
javaFileChecker) {
 results =  javaFileChecker.findPackage("foo");
 moreResults = javaFileChecker.findPackage("bar");



Then return all of the results.  So we would just need a new method in
javaFileChecker for findPackage and just return one search result.  But in
the JavaFileMigrator component we can search for different packages.

On Thu, Jul 23, 2015 at 2:43 AM, Lovett Li <notifications@github.com> wrote:

> Hey Greg,
> The ASTVisitor can visite PackageDeclaration just one. so if we put all of
> the package code into one test file. The ASTVisitor just is able to visite
> the last one. For example , this is our test file
> ” package com.liferay.portlet.bookmarks
> package com.liferay.portlet.dynamicdatalists
> package com.liferay.portlet.journal
> package com.liferay.portlet.polls
> package com.liferay.portlet.wiki “
>
> We want to test all possible case, but PackageDeclaration just is
> "com.liferay.portlet.wiki" all the time.so if we want test all case. My
> idea is put each of package name code into different file and put all the
> file into a folder.
> we can change the test path to a directory.
> what do you think? thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/blade.tools/issues/130#issuecomment-124007638>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by lovettli** [comment]
Yes i did it via this way. Sorry, maybe my expression has a little confuse. 
I created new method "findPackage(final String packageName)" in JavaFileChecker and add a loop code in my component so that i can search multiple packages.But the problem is these code 
"_ast.accept(new ASTVisitor() {
			@Override
			public boolean visit(PackageDeclaration node) {
"
The PackageDeclaration can only get the last package name if the file has multiple package code.So right now our test file contains many package code like this

” package com.liferay.portlet.bookmarks
package com.liferay.portlet.dynamicdatalists
package com.liferay.portlet.journal
package com.liferay.portlet.polls
package com.liferay.portlet.wiki “

The first loop want to find the first one "package com.liferay.portlet.bookmarks".But PackageDeclaration node doesn't contains all of package that it is just last one. So we can only find this package "com.liferay.portlet.wiki “.
The reality java file doesn't be able to exist multiple package code. i guess it is rule of ASTVisitor.
So we don't be able to test many package name in one test file.
what do you think ? thanks.
