### ISSUE TITLE
Removed the DLFileEntryTypes_DDMStructures Mapping Table

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#131]
Date: 2015-Jul-01
https://issues.liferay.com/browse/LPS-56660
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#removed-the-dlfileentrytypes_ddmstructures-mapping-table

type:java

**Comment by gamerson** [comment]
Add the type, thanks.

On Tue, Jul 14, 2015 at 11:41 AM, Lovett Li <notifications@github.com>
wrote:

> Date: 2015-Jul-01
> https://issues.liferay.com/browse/LPS-56660
>
> https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#removed-the-dlfileentrytypes_ddmstructures-mapping-table
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/blade.tools/issues/131>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com
