### ISSUE TITLE
Removed USERS_LAST_NAME_REQUIRED from portal.properties in Favor of language.properties Configurations

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#15]
Date: 2015-May-07
https://issues.liferay.com/browse/LPS-54956
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#removed-users_last_name_required-from-portalproperties-in-favor-of-languageproperties-configurations

**Comment by AndyWu2015** [comment]
Should we check the corresponding filed in PropsKeys and PropsValues (java file) as described in #19
