### ISSUE TITLE
Removed the Type Setting breadcrumbShowParentGroups from Groups

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#18]
Date: 2015-Apr-21
https://issues.liferay.com/browse/LPS-54791
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#removed-the-type-setting-breadcrumbshowparentgroups-from-groups

**Comment by jtydhr88** [comment]
How should I update my code?

There are no code updates required. This should only be updated at the portlet instance level.

We don't need check for it

**Comment by AndyWu2015** [comment]
yeah there are some other issues  with the same type

**Comment by gamerson** [comment]
Sounds good.
