### ISSUE TITLE
Removed Portal Properties Used to Display Sections in Form Navigators

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#19]
Date: 2015-Apr-16
https://issues.liferay.com/browse/LPS-54903
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#removed-portal-properties-used-to-display-sections-in-form-navigators

**Comment by AndyWu2015** [comment]
need check properties file and java file both

**Comment by AndyWu2015** [comment]
found it is already solved with PortalProperties class and PortalPropertiesTest class
