### ISSUE TITLE
Moved Indexer.addRelatedEntryFields and Indexer.reindexDDMStructures, and Removed Indexer.getQueryString

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#2]
Date:2015-May-27
https://issues.liferay.com/browse/LPS-55928
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#moved-indexeraddrelatedentryfields-and-indexerreindexddmstructures-and-removed-indexergetquerystring

**Comment by jtydhr88** [comment]
Need for waiting for Andy finished Invocation function

**Comment by jtydhr88** [comment]
Hi Greg, there is a case:
interface Indexer {
    void reindex();
}

class BaseIndexer implements Indexer{
    void reindex() {
          .....
    }
}

class BlogIndexer extends BaseIndexer {
     .....
}

class MainTest {
     public void main() {
           BlogIndexer bi = new BlogIndexer();
           bi.reindex();
     }
}

now we can't resolve this case yet,right?

**Comment by gamerson** [comment]
So if we are just looking for "Indexer" then yes we can't resolve this...
but what we could do is do some guessing.... lookfor a "reindex" method and then check the type of the object it is invoked on and if it has "indexer"  in the name, we could match that.

Can you try that?  

So just check the "type" binding of the object that "reindex" is called on and if that "type" has the word "Indexer" in it, then we can consider that as a "hit".

**Comment by AndyWu2015** [comment]
yeah we can guess the type , and I think we also need to check if some class implements the Indexer interface and prompt them delete the method in their own class

**Comment by AndyWu2015** [comment]
Hi guys , I have another way , we can just find the implementation of the interface and make notes for developers, as method invocation based on implementation, developers will solve them inevitably.
And we also need to do some guessing about method invocations as Greg said on the meeting.
I am working on it.
