### ISSUE TITLE
Changed the Default Value of the copy-request-parameters Init Parameter for MVC Portlets

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#20]
Date: 2015-Apr-15
https://issues.liferay.com/browse/LPS-54798
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#changed-the-default-value-of-the-copy-request-parameters-init-parameter-for-mvc-portlets

**Comment by jtydhr88** [comment]
Need for waiting for Greg merged the JavaImportMigrator changed

**Comment by AndyWu2015** [comment]
I have finished the superclass check and should we check the property file ?

**Comment by gamerson** [comment]
Its a property file but rather a portlet.xml file that contains these
parameters.

On Mon, Jul 6, 2015 at 5:30 PM, Andy Wu <notifications@github.com> wrote:

> I have finished the superclass check and should we check the property file
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/blade.tools/issues/20#issuecomment-118785553>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by AndyWu2015** [comment]
Yeah I have finished the XML searcher based on SAX but I am not sure if we should add a new file.extensions type — xml for matching xml file or we just check the particular portlet.xml file ?

**Comment by gamerson** [comment]
Lets add it fileMigrator with extension xml and the file migrator can check
if the file name is portlet.xml

On Tue, Jul 14, 2015 at 10:42 AM, Andy Wu <notifications@github.com> wrote:

> Yeah I have finished the XML searcher based on SAX but I am not sure if we
> should add a new file.extensions type — xml for matching xml file or we
> just check the particular portlet.xml file ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/blade.tools/issues/20#issuecomment-121115735>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
Just set the "file.extensions=xml"  and then in the search method check to
see if the file name is "portlet.xml"

On Tue, Jul 14, 2015 at 10:43 AM, Greg Amerson <gregory.amerson@liferay.com>
wrote:

> Lets add it fileMigrator with extension xml and the file migrator can
> check if the file name is portlet.xml
>
> On Tue, Jul 14, 2015 at 10:42 AM, Andy Wu <notifications@github.com>
> wrote:
>
>> Yeah I have finished the XML searcher based on SAX but I am not sure if
>> we should add a new file.extensions type — xml for matching xml file or we
>> just check the particular portlet.xml file ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gamerson/blade.tools/issues/20#issuecomment-121115735>
>> .
>>
>
>
>
> --
> Greg Amerson
> Liferay Developer Tools
> Liferay, Inc. www.liferay.com
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by AndyWu2015** [comment]
Did you mean that we should create a XMLFileMigrator implements FileMigrator or just use the JavaFileMigrator ?

**Comment by gamerson** [comment]
Yes lets create a XMLFileMigrator in the same pattern as others.

On Tue, Jul 14, 2015 at 3:01 PM, Andy Wu <notifications@github.com> wrote:

> Did you mean that we should create a XMLFileMigrator implements
> FileMigrator or just use the JavaFileMigrator ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/blade.tools/issues/20#issuecomment-121148345>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com
