### ISSUE TITLE
Added New Methods in the ScreenNameValidator Interface

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#24]
Date: 2015-Mar-17
https://issues.liferay.com/browse/LPS-53409
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#added-new-methods-in-the-screennamevalidator-interface

**Comment by jtydhr88** [comment]
Need for waiting for Greg merged the JavaImportMigrator changed
