### ISSUE TITLE
Created a New getType Method That is Implemented in DLProcessor

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#30]
Date: 2015-Feb-17
https://issues.liferay.com/browse/LPS-53574
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#created-a-new-gettype-method-that-is-implemented-in-dlprocessor

**Comment by AndyWu2015** [comment]
waiting for merge my code with findInterfaceImplements method
