### ISSUE TITLE
Removed Operations That Used the Fields Class from the StorageAdapter Interface

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#31]
Date: 2015-Feb-11
https://issues.liferay.com/browse/LPS-53021
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#removed-operations-that-used-the-fields-class-from-the-storageadapter-interface

**Comment by gamerson** [comment]
@lovettli take a look at this file:
https://github.com/gamerson/blade.tools/blob/6a7acb66aaaa9c0f76e1a65024d79cdc432dc41e/blade.migrate.liferay70/src/blade/migrate/liferay70/PortletConfigGetFormatMethods.java

for an example of how to do this migrator
