### ISSUE TITLE
Moved the AssetPublisherUtil Class and Removed It from the Public API

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#32]
Date: 2015-Feb-11
https://issues.liferay.com/browse/LPS-52744
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#moved-the-assetpublisherutil-class-and-removed-it-from-the-public-api

**Comment by AndyWu2015** [comment]
already solved by simon
