### ISSUE TITLE
Replaced ReservedUserIdException with UserIdException Inner Classes

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#33]
Date: 2015-Feb-10
https://issues.liferay.com/browse/LPS-53487
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#replaced-reserveduseridexception-with-useridexception-inner-classes

**Comment by jtydhr88** [comment]
Waiting for Greg merged the JavaImportMigrator changed
