### ISSUE TITLE
Added Required Attribute paginationURL to the Tag liferay-ui:discussion

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#34]
Date: 2015-Feb-05
https://issues.liferay.com/browse/LPS-53313
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#added-required-attribute-paginationurl-to-the-tag-liferay-uidiscussion

**Comment by lovettli** [comment]
Hey Greg,
This issues can be find in Google Sheets.But it doesn't appear in "https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#added-required-attribute-paginationurl-to-the-tag-liferay-uidiscussion".
So do we still need to fix it ?

**Comment by gamerson** [comment]
Discuss with Terry and see if you can find where it came from or where it
should be pointing to.

On Sun, Jul 26, 2015 at 10:37 PM, Lovett Li <notifications@github.com>
wrote:

> Hey Greg,
> This issues can be find in Google Sheets.But it doesn't appear in "
> https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#added-required-attribute-paginationurl-to-the-tag-liferay-uidiscussion
> ".
> So do we still need to fix it ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/blade.tools/issues/34#issuecomment-125074600>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by jtydhr88** [comment]
Hi Guy, the case has been remove in 42712154787589bf5544f032195416ed61c8fb99, so we don't need fix it.
