### ISSUE TITLE
Replaced the ReservedUserEmailAddressException with UserEmailAddressException Inner Classes in User Services

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#35]
Date: 2015-Feb-03
https://issues.liferay.com/browse/LPS-53279
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#replaced-the-reserveduseremailaddressexception-with-useremailaddressexception-inner-classes-in-user-services

**Comment by jtydhr88** [comment]
Waiting for Greg merged the JavaImportMigrator changed

**Comment by AndyWu2015** [comment]
already been resolved by simon ...
