### ISSUE TITLE
Replaced the ReservedUserScreenNameException with UserScreenNameException.MustNotBeReserved in UserLocalService

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#36]
Date: 2015-Jan-29
https://issues.liferay.com/browse/LPS-53113
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#replaced-the-reserveduserscreennameexception-with-userscreennameexceptionmustnotbereserved-in-userlocalservice

**Comment by jtydhr88** [comment]
Waiting for Greg merged the JavaImportMigrator changed

**Comment by gamerson** [comment]
We have the method now to check for exceptions.
