### ISSUE TITLE
Removed Support for Flat Thread View in Discussion Comments

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#39]
Date: 2014-Dec-30
https://issues.liferay.com/browse/LPS-51876
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#removed-support-for-flat-thread-view-in-discussion-comments

**Comment by jtydhr88** [comment]
How should I update my code?

There is no need to update anything since the portal property has been removed and the combination thread view is now hard-coded.

We don't need do a check for this problem.
