### ISSUE TITLE
Removed the Header Web Content and Footer Web Content Preferences from the RSS Portlet

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#41]
Date: 2014-Nov-12
https://issues.liferay.com/browse/LPS-46984
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#removed-the-header-web-content-and-footer-web-content-preferences-from-the-rss-portlet

**Comment by jtydhr88** [comment]
I don't think we need do check for this problem.

**Comment by gamerson** [comment]
Agreed
