### ISSUE TITLE
Migration of the Field Type from the Journal Article API into a Vocabulary

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#43]
Date: 2014-Oct-13
https://issues.liferay.com/browse/LPS-50764
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#migration-of-the-field-type-from-the-journal-article-api-into-a-vocabulary

**Comment by AndyWu2015** [comment]
I even didn't see JournalArticle.getType() and JournalFeed.getType() (as pointed in BREAKING_CHANGES )in Liferay6.2 source code ,

**Comment by AndyWu2015** [comment]
I have talked with Brian Wulbern and he said "so the ticket tagging api you linked me isn't very clear" and they are still working on it . So we can wait.
