### ISSUE TITLE
Convert Process Classes Are No Longer Specified via the convert.processes Portal Property, but Are Contributed as OSGi Modules

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#44]
Date: 2014-Oct-09
https://issues.liferay.com/browse/LPS-50604
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#convert-process-classes-are-no-longer-specified-via-the-convertprocesses-portal-property-but-are-contributed-as-osgi-modules

**Comment by AndyWu2015** [comment]
waiting for merge my code with findSpuerClass method

**Comment by AndyWu2015** [comment]
need checking in properties files and wait for Terry's PropertiesFileMigrator
