### ISSUE TITLE
Moved MVCPortlet, ActionCommand and ActionCommandCache from util-bridges.jar to portal-service.jar

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#45]
Date: 2014-Sep-26
type:java
https://issues.liferay.com/browse/LPS-50156
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#moved-mvcportlet-actioncommand-and-actioncommandcache-from-util-bridgesjar-to-portal-servicejar

**Comment by AndyWu2015** [comment]
Hi Greg , 
as it said : "In addition, com.liferay.util.bridges.mvc.MVCPortlet is deprecated, but was made to extend com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet."
Should we check the portlet.xml for finding 
"<portlet-class>com.liferay.util.bridges.mvc.MVCPortlet</portlet-class>" and make a warning ?

**Comment by gamerson** [comment]
Ah yes we should find the old MVCPortlet and mark it as a problem with this
message.  But it should only match MVCPortlet that uses the old package (so
we may hae to search for extends "MVCPortlet" and Imports includes that old
package name.

On Tue, Jul 14, 2015 at 10:24 AM, Andy Wu <notifications@github.com> wrote:

> Hi Greg ,
> as it said : "In addition, com.liferay.util.bridges.mvc.MVCPortlet is
> deprecated, but was made to extend
> com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet."
> Should we check the portlet.xml for finding
> "com.liferay.util.bridges.mvc.MVCPortlet" and make a warning ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/blade.tools/issues/45#issuecomment-121114177>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by AndyWu2015** [comment]
Yeah ,  Could  you fix it since we have findSuperClass method in JavaFileChecker ? I just notice you that. Haha
