### ISSUE TITLE
Removed Trash Logic from DLAppHelperLocalService Methods

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#48]
Date: 2014-Jul-22
type:java,jsp
https://issues.liferay.com/browse/LPS-47508
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#removed-trash-logic-from-dlapphelperlocalservice-methods

**Comment by AndyWu2015** [comment]
What is the type ? java ? or java,jsp ?

**Comment by gamerson** [comment]
java,jsp

**Comment by jtydhr88** [comment]
Fixed in https://github.com/gamerson/blade.tools/pull/103

**Comment by jtydhr88** [comment]
Fixed in https://github.com/gamerson/blade.tools/pull/103
