### ISSUE TITLE
Changes in Exceptions Thrown by User Services

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#49]
Date: 2014-Jul-03
https://issues.liferay.com/browse/LPS-47130
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#changes-in-exceptions-thrown-by-user-services

**Comment by aquilabj** [comment]
https://github.com/gamerson/blade.tools/pull/80

**Comment by gamerson** [comment]
Fixed by #80
