### ISSUE TITLE
The aui:input Tag for Type checkbox No Longer Creates a Hidden Input

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#51]
Date: 2014-Jun-16
https://issues.liferay.com/browse/LPS-44228
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#the-auiinput-tag-for-type-checkbox-no-longer-creates-a-hidden-input

type: javasrcipt

**Comment by lovettli** [comment]
Hey Greg,
Sorry i am not very clear about what's this issue want to find?
I find some codes like this

```
var inputs = A.one(form).all('input[type=checkbox]');
```
which part of code do we need to search?

**Comment by gamerson** [comment]
I see this is for javascript only, so we wont tackle this with blade.tools.
