### ISSUE TITLE
Only One Portlet Instance's Settings is Used Per Portlet

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#53]
Date: 2014-Jun-06
https://issues.liferay.com/browse/LPS-43134
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#only-one-portlet-instances-settings-is-used-per-portlet

**Comment by jtydhr88** [comment]
I don't think there are any codes we need check for this problem.

**Comment by gamerson** [comment]
Agreed.
