### ISSUE TITLE
Merged Configured Email Signature Field into the Body of Email Messages from Message Boards and Wiki

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#57]
Date: 2014-Feb-28
https://issues.liferay.com/browse/LPS-44599
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#merged-configured-email-signature-field-into-the-body-of-email-messages-from-message-boards-and-wiki

type:properties

**Comment by jtydhr88** [comment]
Fixed on https://github.com/gamerson/blade.tools/pull/66
