### ISSUE TITLE
Removed mbMessages and fileEntryTuples Attributes from app-view-search-entry Tag

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#59]
Date: 2015-May-27
https://issues.liferay.com/browse/LPS-55886
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#removed-mbmessages-and-fileentrytuples-attributes-from-app-view-search-entry-tag

type:jsp

**Comment by lovettli** [comment]
Hey Greg,
This issue involve java and jsp problems. Do we need create two migrators or just one JSPTagsFileMigrator ? If we  need  one migrator how to design our JUnit test file ?

**Comment by gamerson** [comment]
We should create two components one of them a JavaFileMigrator and another
one a JSPTagsFileMigrator and we can just modify the title and summaries
accordingly.

On Mon, Jul 27, 2015 at 3:21 AM, Lovett Li <notifications@github.com> wrote:

> Hey Greg,
> This issue involve java and jsp problems. Do we need create two migrators
> or just one JSPTagsFileMigrator ? If we need one migrator how to design our
> JUnit test file ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/blade.tools/issues/59#issuecomment-125122696>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by lovettli** [comment]
ok,got it.
