### ISSUE TITLE
Removed Method getEntries from DL, DLImpl, and DLUtil Classes

### ISSUE THREAD

**Issue by lovettli** [gamerson/blade.tools#62]
Date: 2015-Jun-10
https://issues.liferay.com/browse/LPS-56247
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#removed-method-getentries-from-dl-dlimpl-and-dlutil-classes

type:java,jsp

**Comment by gamerson** [comment]
This should be possible now that the new type checker is merged.

**Comment by AndyWu2015** [comment]
java file check done , and wait for the jsp file checking finished

**Comment by gamerson** [comment]
Closing for now we can reopen once we do jsps.
